name: projectpractice
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^2.0.1+1
  json_annotation: ^2.0.0
  shared_preferences: "^0.4.2"
  flutter_swiper: ^1.0.6
  fijkplayer: ^0.2.2 
  image_picker: ^0.6.0+9
  dio: ^2.1.0
  fluttertoast: ^3.1.3
  flutter_alipay: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  json_model: ^0.0.2 #最新版本
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/course-bg1.jpg
     - images/course-bg2.png
     - images/course-bg3.png
     - images/courser-bg4.png
     - images/courser-bg5.png
     - images/courser-bg6.png
     - images/courser-bg7.png
     - images/course1.jpg
     - images/course2.jpg
     - images/course3.png
     - images/course4.jpg
     - images/Angular.png
     - images/Bootstrap.png
     - images/html.png
     - images/html5.png
     - images/jQuery.png
     - images/JS.png
     - images/Nodejs.png
     - images/React.png
     - images/SASS.png
     - images/tools.png
     - images/Vue.png
     - images/xioacx.png
     - images/studybg.jpg    
     - images/personbg1.jpg
     - images/header1.jpeg
     - images/sex-woman.png
     - images/loginbg.png
     - images/courseLogo.png
     - images/weixinlogin.png
     - images/courselistbg1.jpg 
     - images/courselist-1.jpg
     - images/zhifubao.png
     - images/weixinpay.png
     - images/jingdozhifu.png
     - images/bg3.jpg
     - images/bg4.jpg
     - images/infotip.jpg
     - images/gift.png
     - images/unloginbg1.jpg
     - images/man.png
     - images/bg111.jpg
     - images/qidon1.jpg
     - images/qidon2.jpg
       
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
